/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectRouteImport } from './routes/$project'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProjectIndexRouteImport } from './routes/$project.index'
import { Route as ProjectDocsRouteImport } from './routes/$project.docs'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectDocsIndexRouteImport } from './routes/$project.docs.index'
import { Route as ProjectDocsSplatRouteImport } from './routes/$project.docs.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRoute = ProjectRouteImport.update({
  id: '/$project',
  path: '/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectRoute,
} as any)
const ProjectDocsRoute = ProjectDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => ProjectRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectDocsIndexRoute = ProjectDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectDocsRoute,
} as any)
const ProjectDocsSplatRoute = ProjectDocsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ProjectDocsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$project': typeof ProjectRouteWithChildren
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/search': typeof SearchRoute
  '/$project/docs': typeof ProjectDocsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/$project/': typeof ProjectIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/$project/docs/$': typeof ProjectDocsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$project/docs/': typeof ProjectDocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/search': typeof SearchRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/$project': typeof ProjectIndexRoute
  '/blog': typeof BlogIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/$project/docs/$': typeof ProjectDocsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$project/docs': typeof ProjectDocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$project': typeof ProjectRouteWithChildren
  '/admin': typeof AdminRoute
  '/privacy': typeof PrivacyRoute
  '/rules': typeof RulesRoute
  '/search': typeof SearchRoute
  '/$project/docs': typeof ProjectDocsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/$project/': typeof ProjectIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/$project/docs/$': typeof ProjectDocsSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$project/docs/': typeof ProjectDocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$project'
    | '/admin'
    | '/privacy'
    | '/rules'
    | '/search'
    | '/$project/docs'
    | '/blog/$slug'
    | '/$project/'
    | '/blog/'
    | '/projects/'
    | '/$project/docs/$'
    | '/api/auth/$'
    | '/$project/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/privacy'
    | '/rules'
    | '/search'
    | '/blog/$slug'
    | '/$project'
    | '/blog'
    | '/projects'
    | '/$project/docs/$'
    | '/api/auth/$'
    | '/$project/docs'
  id:
    | '__root__'
    | '/'
    | '/$project'
    | '/admin'
    | '/privacy'
    | '/rules'
    | '/search'
    | '/$project/docs'
    | '/blog/$slug'
    | '/$project/'
    | '/blog/'
    | '/projects/'
    | '/$project/docs/$'
    | '/api/auth/$'
    | '/$project/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectRoute: typeof ProjectRouteWithChildren
  AdminRoute: typeof AdminRoute
  PrivacyRoute: typeof PrivacyRoute
  RulesRoute: typeof RulesRoute
  SearchRoute: typeof SearchRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$project': {
      id: '/$project'
      path: '/$project'
      fullPath: '/$project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$project/': {
      id: '/$project/'
      path: '/'
      fullPath: '/$project/'
      preLoaderRoute: typeof ProjectIndexRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/$project/docs': {
      id: '/$project/docs'
      path: '/docs'
      fullPath: '/$project/docs'
      preLoaderRoute: typeof ProjectDocsRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$project/docs/': {
      id: '/$project/docs/'
      path: '/'
      fullPath: '/$project/docs/'
      preLoaderRoute: typeof ProjectDocsIndexRouteImport
      parentRoute: typeof ProjectDocsRoute
    }
    '/$project/docs/$': {
      id: '/$project/docs/$'
      path: '/$'
      fullPath: '/$project/docs/$'
      preLoaderRoute: typeof ProjectDocsSplatRouteImport
      parentRoute: typeof ProjectDocsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectDocsRouteChildren {
  ProjectDocsSplatRoute: typeof ProjectDocsSplatRoute
  ProjectDocsIndexRoute: typeof ProjectDocsIndexRoute
}

const ProjectDocsRouteChildren: ProjectDocsRouteChildren = {
  ProjectDocsSplatRoute: ProjectDocsSplatRoute,
  ProjectDocsIndexRoute: ProjectDocsIndexRoute,
}

const ProjectDocsRouteWithChildren = ProjectDocsRoute._addFileChildren(
  ProjectDocsRouteChildren,
)

interface ProjectRouteChildren {
  ProjectDocsRoute: typeof ProjectDocsRouteWithChildren
  ProjectIndexRoute: typeof ProjectIndexRoute
}

const ProjectRouteChildren: ProjectRouteChildren = {
  ProjectDocsRoute: ProjectDocsRouteWithChildren,
  ProjectIndexRoute: ProjectIndexRoute,
}

const ProjectRouteWithChildren =
  ProjectRoute._addFileChildren(ProjectRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectRoute: ProjectRouteWithChildren,
  AdminRoute: AdminRoute,
  PrivacyRoute: PrivacyRoute,
  RulesRoute: RulesRoute,
  SearchRoute: SearchRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
